# Generated by Django 3.1.1 on 2020-09-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('url', models.URLField()),
                ('newspaper_uid', models.CharField(max_length=100)),
                ('host', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
    ]
